/**
 * Unit tests for the Reporting Engine module.
 *
 * These tests verify:
 * - Template configuration per report type
 * - PDF generation utility
 * - Zod schema validation
 */

import { getTemplateConfig } from './templates';
import { markdownToPdf } from './pdf';
import { generateReportBodySchema, reportDownloadQuerySchema } from './schemas';

// ---------------------------------------------------------------------------
// Template config tests (pure, no DB required)
// ---------------------------------------------------------------------------

describe('Report Templates', () => {
  it('should return valid template config for all report types', () => {
    const types = ['DAILY', 'WEEKLY', 'EXECUTIVE', 'COMPLIANCE', 'RISK', 'PROCUREMENT'] as const;

    for (const type of types) {
      const config = getTemplateConfig(type);
      expect(config).toBeDefined();
      expect(config.type).toBe(type);
      expect(config.title).toBeTruthy();
      expect(config.sections.length).toBeGreaterThan(0);
    }
  });

  it('WEEKLY template should include all sections', () => {
    const config = getTemplateConfig('WEEKLY');
    expect(config.sections).toContain('executive');
    expect(config.sections).toContain('documents');
    expect(config.sections).toContain('compliance');
    expect(config.sections).toContain('schedule');
    expect(config.sections).toContain('procurement');
    expect(config.sections).toContain('rfis');
    expect(config.sections).toContain('risks');
    expect(config.sections).toContain('recommendations');
    expect(config.sections.length).toBe(8);
  });

  it('COMPLIANCE template should include only compliance-related sections', () => {
    const config = getTemplateConfig('COMPLIANCE');
    expect(config.sections).toContain('executive');
    expect(config.sections).toContain('compliance');
    expect(config.sections).toContain('recommendations');
    expect(config.sections).not.toContain('schedule');
    expect(config.sections).not.toContain('procurement');
  });

  it('EXECUTIVE template should not include documents or rfis sections', () => {
    const config = getTemplateConfig('EXECUTIVE');
    expect(config.sections).not.toContain('documents');
    expect(config.sections).not.toContain('rfis');
    expect(config.sections).toContain('executive');
    expect(config.sections).toContain('risks');
  });

  it('PROCUREMENT template should focus on procurement', () => {
    const config = getTemplateConfig('PROCUREMENT');
    expect(config.sections).toContain('procurement');
    expect(config.sections).toContain('executive');
    expect(config.sections).not.toContain('schedule');
    expect(config.sections).not.toContain('compliance');
  });

  it('RISK template should include schedule and procurement for risk context', () => {
    const config = getTemplateConfig('RISK');
    expect(config.sections).toContain('schedule');
    expect(config.sections).toContain('procurement');
    expect(config.sections).toContain('risks');
    expect(config.sections).toContain('recommendations');
  });

  it('DAILY template should cover core operational sections', () => {
    const config = getTemplateConfig('DAILY');
    expect(config.sections).toContain('documents');
    expect(config.sections).toContain('compliance');
    expect(config.sections).toContain('schedule');
    expect(config.sections).toContain('procurement');
    expect(config.sections).toContain('rfis');
  });
});

// ---------------------------------------------------------------------------
// PDF utility tests (can run without DB)
// ---------------------------------------------------------------------------

describe('PDF Generator', () => {
  it('should export markdownToPdf function', () => {
    expect(typeof markdownToPdf).toBe('function');
  });

  it('should generate a PDF buffer from simple markdown', async () => {
    const markdown = `# Test Report

## Section 1

This is a test paragraph.

| Column A | Column B |
|----------|----------|
| Value 1 | Value 2 |

---

> This is a blockquote.

*Generated by test suite*`;

    const buffer = await markdownToPdf(markdown, {
      title: 'Test Report',
      projectName: 'Test Project',
      generatedAt: new Date().toISOString(),
    });

    expect(Buffer.isBuffer(buffer)).toBe(true);
    expect(buffer.length).toBeGreaterThan(0);

    // PDF files start with %PDF
    const pdfHeader = buffer.subarray(0, 5).toString('ascii');
    expect(pdfHeader).toBe('%PDF-');
  });

  it('should handle empty markdown', async () => {
    const buffer = await markdownToPdf('', {
      title: 'Empty Report',
      projectName: 'Test',
      generatedAt: new Date().toISOString(),
    });

    expect(Buffer.isBuffer(buffer)).toBe(true);
    expect(buffer.length).toBeGreaterThan(0);
  });
});

// ---------------------------------------------------------------------------
// Schema validation tests
// ---------------------------------------------------------------------------

describe('Report Schemas', () => {
  it('should validate generateReportBodySchema', () => {
    const valid = generateReportBodySchema.parse({ type: 'EXECUTIVE' });
    expect(valid.type).toBe('EXECUTIVE');
    expect(valid.runAsync).toBe(false);

    const withAsync = generateReportBodySchema.parse({ type: 'DAILY', runAsync: true });
    expect(withAsync.runAsync).toBe(true);
  });

  it('should reject invalid report type', () => {
    expect(() => generateReportBodySchema.parse({ type: 'INVALID' })).toThrow();
  });

  it('should validate reportDownloadQuerySchema', () => {
    expect(reportDownloadQuerySchema.parse({}).format).toBe('pdf');
    expect(reportDownloadQuerySchema.parse({ format: 'md' }).format).toBe('md');
  });
});
