upstream minio_s3_upstream {
    server 127.0.0.1:9005;
    keepalive 16;
}

server {
    listen 80;
    server_name storage-dcbrain.nebula-hack.tech;

    # To allow special characters in headers
    ignore_invalid_headers off;
    
    # Allow any size file to be uploaded.
    # Set to a value such as 1000m; to restrict file size to a specific value
    client_max_body_size 1G;
    
    # Disable buffering
    proxy_buffering off;
    proxy_request_buffering off;

    # Security headers
    add_header X-Frame-Options                "DENY" always;
    add_header X-Content-Type-Options         "nosniff" always;
    add_header X-XSS-Protection               "1; mode=block" always;
    add_header Referrer-Policy                "strict-origin-when-cross-origin" always;
    add_header X-Request-ID $request_id always;

    # CORS configuration to allow public viewing and downloading of files
    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Authorization, Content-Type, Accept, Origin, User-Agent, DNT, Cache-Control, X-Mx-ReqToken, Keep-Alive, X-Requested-With, If-Modified-Since" always;

    location / {
        # Handle CORS preflight requests
        if ($request_method = 'OPTIONS') {
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Authorization, Content-Type, Accept, Origin, User-Agent, DNT, Cache-Control, X-Mx-ReqToken, Keep-Alive, X-Requested-With, If-Modified-Since" always;
            add_header Access-Control-Max-Age 1728000;
            add_header Content-Type 'text/plain; charset=utf-8';
            add_header Content-Length 0;
            return 204;
        }

        proxy_pass http://minio_s3_upstream;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Request-ID $request_id;

        proxy_connect_timeout 300;
        
        # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        chunked_transfer_encoding off;
    }
}
