/**
 * Generates the deliverable planning artefacts from a live scan of the dataset:
 *   • UPLOAD_PLAN.md       — human-readable table, every file exactly once
 *   • upload-map.json      — machine-readable relPath -> {module, page, category, metadata}
 *   • UPLOAD_GAP_ANALYSIS.md — modules without upload support & recommendations
 *
 * Run:  pnpm plan   (or  npm run plan  /  tsx src/generatePlan.ts)
 *
 * This is pure analysis — it never opens a browser or touches the platform.
 */

import fs from 'node:fs';
import path from 'node:path';
import { scanDataset, repoRoot } from './scanner.js';
import baseConfig from '../upload.config.js';
import type { ClassifiedFile, Destination } from './types.js';

const DEST_ORDER: Destination[] = ['Documents', 'Procurement', 'Schedule Risk', 'Excluded'];

function fmtBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(2)} MB`;
}

function metaString(m: Record<string, string>): string {
  return Object.entries(m)
    .map(([k, v]) => `${k}=${v}`)
    .join('; ');
}

function groupByDestination(files: ClassifiedFile[]): Map<Destination, ClassifiedFile[]> {
  const map = new Map<Destination, ClassifiedFile[]>();
  for (const d of DEST_ORDER) map.set(d, []);
  for (const f of files) map.get(f.destination)!.push(f);
  return map;
}

export function buildPlan(datasetRoot: string): {
  files: ClassifiedFile[];
  planMd: string;
  gapMd: string;
  map: Record<string, unknown>;
  summary: Record<Destination, number>;
} {
  const { files } = scanDataset(datasetRoot);
  const grouped = groupByDestination(files);

  const summary = {} as Record<Destination, number>;
  for (const d of DEST_ORDER) summary[d] = grouped.get(d)!.length;

  // ---- UPLOAD_PLAN.md ----
  const lines: string[] = [];
  lines.push('# DCBrain Demo-Data — Upload Plan');
  lines.push('');
  lines.push(`_Generated by \`demo-uploader\` from a live scan of \`${datasetRoot}\`._`);
  lines.push('');
  lines.push('Every discovered file appears exactly once. Routing is derived from the three real upload controls in DCBrain (Documents, Procurement, Schedule Risk); files that are dataset-generation or evaluation artefacts are listed under **Excluded** with a reason.');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Destination | Files |');
  lines.push('|-------------|------:|');
  for (const d of DEST_ORDER) lines.push(`| ${d} | ${summary[d]} |`);
  lines.push(`| **Total** | **${files.length}** |`);
  lines.push('');

  for (const d of DEST_ORDER) {
    const group = grouped.get(d)!;
    if (group.length === 0) continue;
    lines.push(`## ${d} (${group.length})`);
    lines.push('');
    if (d === 'Excluded') {
      lines.push('| File | EPC Category | Reason |');
      lines.push('|------|--------------|--------|');
      for (const f of group) {
        lines.push(`| \`${f.relPath}\` | ${f.epcCategory} | ${f.excludeReason ?? ''} |`);
      }
    } else {
      lines.push('| File | Upload Page | Category | Business Purpose | Metadata |');
      lines.push('|------|-------------|----------|------------------|----------|');
      for (const f of group) {
        lines.push(
          `| \`${f.relPath}\` | ${f.page} | ${f.category} | ${f.businessPurpose} | ${metaString(f.metadata)} |`,
        );
      }
    }
    lines.push('');
  }
  const planMd = lines.join('\n');

  // ---- upload-map.json ----
  const map: Record<string, unknown> = {};
  for (const f of files) {
    map[f.relPath] = {
      module: f.destination,
      page: f.page ?? null,
      category: f.category,
      epcCategory: f.epcCategory,
      businessPurpose: f.businessPurpose,
      aiUsage: f.aiUsage,
      pipeline: f.pipeline,
      metadata: f.metadata,
      ext: f.ext,
      sizeBytes: f.sizeBytes,
      ...(f.excludeReason ? { excludeReason: f.excludeReason } : {}),
    };
  }

  // ---- UPLOAD_GAP_ANALYSIS.md ----
  const gapMd = buildGapAnalysis(grouped);

  return { files, planMd, gapMd, map, summary };
}

function buildGapAnalysis(grouped: Map<Destination, ClassifiedFile[]>): string {
  const procDocs = (grouped.get('Documents') ?? []).filter((f) => f.epcCategory === 'Procurement').length;
  const g: string[] = [];
  g.push('# DCBrain — Upload Gap Analysis');
  g.push('');
  g.push('DCBrain exposes exactly **three** user-facing upload/import controls. Every other module derives its data from these three or from in-app generation. This is by design, but it means several disciplines have **no dedicated upload path** and rely on the Documents RAG store.');
  g.push('');
  g.push('## Modules WITH upload support');
  g.push('');
  g.push('| Module | Route | Control | Accepts |');
  g.push('|--------|-------|---------|---------|');
  g.push('| Documents | `/documents` | Drag-drop modal, `files[]` (≤50/batch) | pdf, docx, xlsx, csv, json, xml, txt, md, png, jpg, jpeg, tif, tiff |');
  g.push('| Procurement | `/procurement` | Single-file import, `file` | csv, xlsx (rows keyed on Material + Vendor) |');
  g.push('| Schedule Risk | `/schedule` | Single-file / drag-drop import, `file` | xml (Primavera P6) |');
  g.push('');
  g.push('## Modules WITHOUT upload support (data is derived)');
  g.push('');
  g.push('| Module | Route | How it receives data | Depends on |');
  g.push('|--------|-------|----------------------|-----------|');
  g.push('| Compliance | `/compliance` | Runs standards checks over uploaded documents | Documents |');
  g.push('| RFIs | `/rfis` | Created in-app; AI suggests answers from RAG | Documents |');
  g.push('| NCRs | `/ncrs` | Created in-app | — |');
  g.push('| Inspections | `/inspections` | Created in-app | — |');
  g.push('| Commissioning | `/commissioning` | Created in-app / derived | Documents |');
  g.push('| Quality | `/quality` | Aggregated from QA/QC records | Documents |');
  g.push('| Change Orders | `/change-orders` | Created in-app | — |');
  g.push('| Reports | `/reports` | Generated by the platform (PDF/MD) | all modules |');
  g.push('| Simulations | `/simulations` | Run over imported schedule | Schedule Risk |');
  g.push('| Graph | `/graph` | Neo4j dependency/failure graph | Schedule + Procurement |');
  g.push('| Agents | `/agents` | Triggered by uploads/imports | all modules |');
  g.push('');
  g.push('## Identified gaps & recommendations');
  g.push('');
  g.push('### 1. Procurement importer schema mismatch (HIGH)');
  g.push('The procurement importer keys each row on a `Material` / `Vendor` column. Several demo tables use different headers (`description`, `equipment_id`, banner title rows in XLSX). Those files are therefore routed to **Documents** (so they are still indexed for RAG) rather than the procurement pipeline, and only the schema-matching tables are imported.');
  g.push('');
  g.push(`- **Affected:** procurement registers, summaries, matrices, and PDFs (${procDocs} procurement files routed to Documents).`);
  g.push('- **Recommendation:** add a header-mapping / preview step to `/procurement` import, or normalise the demo CSVs to the importer schema (`Material`, `Vendor`, `PO Number`, `Quantity`, `Status`, `Required On Site Date`).');
  g.push('- **Effort:** ~0.5 day (backend header-alias map) or ~1 day (UI column mapper).');
  g.push('');
  g.push('### 2. No bulk/folder upload for Documents (MEDIUM)');
  g.push('Documents upload is capped at 50 files per batch and has no recursive/folder mode. Large disciplines must be uploaded in multiple batches (the automation handles this transparently).');
  g.push('- **Recommendation:** optional server-side zip ingestion, or a "upload folder" affordance.');
  g.push('- **Effort:** ~1–2 days.');
  g.push('');
  g.push('### 3. No direct upload for Compliance / RFI evidence (LOW)');
  g.push('Compliance and RFI modules cannot attach source files directly; they reference documents already in the RAG store. This is acceptable given the architecture — uploading the compliance/RFI PDFs to Documents makes them available to those modules.');
  g.push('- **Recommendation:** none required for the demo; consider per-module attachment in future.');
  g.push('');
  g.push('> **Conclusion:** no new features are required to upload the full dataset. The automation routes every file to the correct existing control, imports schema-matching procurement tables, and indexes the remaining procurement tables + all discipline documents through Documents.');
  return g.join('\n');
}

// --- CLI entrypoint ---
function main(): void {
  const root = repoRoot();
  const datasetRoot = process.argv[2] ?? baseConfig.datasetRoot;
  const { planMd, gapMd, map, summary, files } = buildPlan(datasetRoot);

  const outPlan = path.join(root, 'UPLOAD_PLAN.md');
  const outMap = path.join(root, 'upload-map.json');
  const outGap = path.join(root, 'UPLOAD_GAP_ANALYSIS.md');

  fs.writeFileSync(outPlan, planMd);
  fs.writeFileSync(outMap, JSON.stringify(map, null, 2));
  fs.writeFileSync(outGap, gapMd);

  // eslint-disable-next-line no-console
  console.log('Wrote:');
  console.log(`  ${outPlan}`);
  console.log(`  ${outMap}`);
  console.log(`  ${outGap}`);
  console.log('\nSummary:');
  for (const [dest, n] of Object.entries(summary)) console.log(`  ${dest.padEnd(14)} ${n}`);
  console.log(`  ${'TOTAL'.padEnd(14)} ${files.length}`);
}

// Execute when run directly.
main();
